spring:
  application:
    name: UserService
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness-user
    username: postgres
    password: shivparvati

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081
